version: '3.1'
services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: p
      POSTGRES_USER: postgres
      POSTGRES_DB: asyncio_el
    ports:
      - "5431:5432"